# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features
baseURL = 'https://marigold1287.github.io/'
languageCode = 'en-us'
title = "YURIGRAMMING -Marigold's blog-"
theme = "PaperMod"
mainSections = ['posts']

[params.homeInfoParams]
 Title =  "Yurigramming"
 Content =  """
 私の活動記録
 """
[params]
env = "production"              #enhanced SEO
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true


# for search
# https://fusejs.io/api/options.html
[fuseOpts]
isCaseSensitive = false
shouldSort =true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]
[outputs]                       #search対象
home = ["HTML", "RSS", "JSON"]

[[menu.main]]
identifier = "a"
name = "diary"
url="/categories/diary"
weight = 1
[[menu.main]]
identifier = "post"
name = "article"
url="/categories/article"
weight = 10
[[menu.main]]
identifier = "Tag"
name = "Tag"
url="/tags/"
weight = 20
[[menu.main]]
identifier = "Categories"
name = "Categories"
url="/categories/"
weight = 20
[[menu.main]]
identifier = "Archive"
name = "Archive"
url="/Archives/"
weight = 30
[[menu.main]]
identifier = "Search"
name = "search"
url="/search/"
weight = 40
